apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: retrodep-ffia
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: retrodep-ffia
    app.kubernetes.io/part-of: test-app-684
  name: retrodep-ffia
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-retrodep
      app.kubernetes.io/instance: retrodep-ffia
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-retrodep
        app.kubernetes.io/instance: retrodep-ffia
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-684/retrodep-ffia@sha256:45d01c59626a9a6d9b5b583948cab7386f19956bf8b6e269988dacae1d0558d4
        name: my-retrodep
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
